Adding network space support for http interface.
juju-solutions/interface-http pull request #12
Opened 2018-01-16 18:04 UTC by hyperbolic2346

This consists of using network_get instead of hookenv.unit_get('private-address'). We fall back to private-address if network_get doesn't include ingress information.

2018-01-16 19:20 UTC, Cynerva commented
Looks good to me.

@kwmonroe @johnsca could y'all review this too? interface-http is widely used so it'd definitely be good to have extra eyes on this in case I'm missing something. Thanks.

2018-01-17 06:33 UTC, johnsca commented
Is `ingress-address` what we want here?  I would assume that we use the private address by default to keep all traffic for the relation cloud-internal.  Is the `ingress-address` the public-facing address?

2018-01-17 14:36 UTC, Cynerva commented
Thanks @johnsca. In my testing, ingress-address has always been the same as private-address. My understanding from the [Charm Network Primitives](https://jujucharms.com/docs/2.3/developer-network-primitives) doc is that it only becomes the public-address if you pass a specific relation ID to network-get, and that relation is cross-model.

We're not trying to add cross-model relation support in this PR, we just want interface-http to respect network space bindings. For that, using either `bind-address` or `ingress-address` should work, but the intention seems to be for charm developers to use `ingress-address` when advertising an address to other units.

2018-01-17 15:05 UTC, johnsca approved these changes
Great.  Thanks for the clarification!

2018-01-17 15:08 UTC, johnsca requested changes
Actually, it's possible for `hookenv.network_get()` to raise `NotImplementedError` on older Juju versions, so that should be handled.

2018-01-18 00:03 UTC, hyperbolic2346 commented
How does that look, @johnsca ?

2018-01-18 08:18 UTC, johnsca approved these changes

2018-01-18 08:18 UTC, merged